// Generated by installer/build-windows-installer.ps1. Do not edit by hand.
namespace AmanorsacInstaller;

internal static class BuildInfo
{
    public const string ProductName = "Amanorsac Analog Bundle";
    public const string Version = "1.0.0";
    public const int PluginCount = 10;
}
