#include "common/dsp/AnchorDSP.h"
#include "common/state/PluginSpec.h"
#include <juce_audio_processors/juce_audio_processors.h>
#include <cmath>
#include <iostream>
namespace{
class H final:public juce::AudioProcessor{public:explicit H(const amanorsac::PluginSpec&s):AudioProcessor(BusesProperties().withInput("I",juce::AudioChannelSet::stereo(),true).withOutput("O",juce::AudioChannelSet::stereo(),true)),state(*this,nullptr,"T",amanorsac::PluginSpec::createParameterLayout(s)){}void prepareToPlay(double,int)override{}void releaseResources()override{}bool isBusesLayoutSupported(const BusesLayout&l)const override{return l.getMainInputChannelSet()==l.getMainOutputChannelSet();}void processBlock(juce::AudioBuffer<float>&,juce::MidiBuffer&)override{}juce::AudioProcessorEditor*createEditor()override{return nullptr;}bool hasEditor()const override{return false;}const juce::String getName()const override{return"H";}bool acceptsMidi()const override{return false;}bool producesMidi()const override{return false;}bool isMidiEffect()const override{return false;}double getTailLengthSeconds()const override{return 0;}int getNumPrograms()override{return 1;}int getCurrentProgram()override{return 0;}void setCurrentProgram(int)override{}const juce::String getProgramName(int)override{return{};}void changeProgramName(int,const juce::String&)override{}void getStateInformation(juce::MemoryBlock&)override{}void setStateInformation(const void*,int)override{}juce::AudioProcessorValueTreeState state;};
bool set(juce::AudioProcessorValueTreeState&s,const juce::String&id,float v){if(auto*p=s.getParameter(id)){p->setValueNotifyingHost(p->convertTo0to1(v));return true;}return false;}int fail(const juce::String&m){std::cerr<<"FAIL: "<<m<<std::endl;return 1;}}
int main(){const auto spec=amanorsac::PluginSpec::fromEmbeddedJson();if(spec.id!="D04"&&spec.id!="D05"&&spec.id!="D06")return fail("Unexpected");H h(spec);juce::String focus;float focusValue;double tone=1000;
if(spec.id=="D04"){focus="threshold";focusValue=-12;set(h.state,focus,focusValue);set(h.state,"ceiling",-1);set(h.state,"lookahead",1);}
else if(spec.id=="D05"){focus="threshold";focusValue=-50;set(h.state,focus,focusValue);set(h.state,"range",12);set(h.state,"focus",6000);set(h.state,"attack",.1f);tone=6000;}
else{focus="depth";focusValue=90;set(h.state,focus,focusValue);set(h.state,"sensitivity",100);set(h.state,"speed",100);tone=486;}
for(const auto rate:{44100.0,96000.0,192000.0})for(const auto bs:{32,256,1024}){amanorsac::AnchorDSP dsp;dsp.prepare(rate,bs,2);juce::AudioBuffer<float>z(2,bs);z.clear();dsp.process(z,h.state,spec.id);if(z.getMagnitude(0,bs)>1e-7f)return fail("Silence");double phase=0,diff=0;float maxOut=0;const auto blocks=juce::jmax(12,static_cast<int>(std::ceil(rate*.12/bs)));for(int block=0;block<blocks;++block){juce::AudioBuffer<float>b(2,bs);for(int i=0;i<bs;++i){const auto v=static_cast<float>(.9*std::sin(phase));phase+=juce::MathConstants<double>::twoPi*tone/rate;b.setSample(0,i,v);b.setSample(1,i,v);}juce::AudioBuffer<float>d;d.makeCopyOf(b);dsp.process(b,h.state,spec.id);for(int i=0;i<bs;++i){const auto out=b.getSample(0,i);if(!std::isfinite(out))return fail("Finite");maxOut=juce::jmax(maxOut,std::abs(out));const auto x=out-d.getSample(0,i);diff+=x*x;}}if(diff<1e-7)return fail("No processing "+juce::String(rate)+"/"+juce::String(bs));if(spec.id=="D04"&&maxOut>juce::Decibels::decibelsToGain(-1.0f)+.002f)return fail("Ceiling exceeded");}
const auto saved=h.state.copyState();set(h.state,focus,0);h.state.replaceState(saved.createCopy());if(std::abs(h.state.getRawParameterValue(focus)->load()-focusValue)>.01f)return fail("State");std::cout<<"PASS: "<<spec.id<<" digital control matrix"<<std::endl;return 0;}
