// Writes presets/factory/D0x_factory.json for the digital line.
// Values are in real units and use the expanded contract ids, so an indexed
// control is addressed as band.01.gain. Anything a preset leaves out keeps the
// contract default.
import { writeFileSync, readFileSync } from "node:fs";

const bank = (id, presets) => ({
  plugin_id: id,
  bank: "Amanorsac Digital",
  author: "Amanorsac Studio",
  note: "Factory bank. Starting points, not destinations.",
  categories: [...new Set(presets.map((p) => p.category))],
  presets,
});

const p = (name, category, tags, values) => ({ name, category, tags, values });

// --- helpers for the indexed families -------------------------------------
const pad = (n) => String(n).padStart(2, "0");
/** eq(1, {frequency: 80, gain: -2, q: 0.9, type: "bell"}) -> band.01.* */
const slot = (family, index, fields) =>
  Object.fromEntries(Object.entries(fields).map(([k, v]) => [`${family}.${pad(index)}.${k}`, v]));
const bands = (list) => Object.assign({}, ...list.map((f, i) => slot("band", i + 1, f)));
const zones = (list) => Object.assign({}, ...list.map((f, i) => slot("zone", i + 1, f)));
const taps = (list) => Object.assign({}, ...list.map((f, i) => slot("tap", i + 1, f)));
const xovers = (list) => Object.assign({}, ...list.map((f, i) => slot("xover", i + 1, { frequency: f })));
/** Bands past the ones a preset uses are switched out so they cannot colour it. */
const onlyBands = (count, total, key = "enabled") => {
  const out = {};
  for (let i = count + 1; i <= total; ++i) out[`band.${pad(i)}.${key}`] = false;
  return out;
};

// =========================================================== D01 PRISM EQ
const eq = (list) => ({ ...bands(list.map((b) => ({ ...b, enabled: true }))), ...onlyBands(list.length, 24) });
const d01 = bank("D01", [
  p("Open Vocal", "Vocals", { Source: "Lead Vocal", Intent: "Clarity", Intensity: "Medium" },
    { ...eq([{ type: "low_cut", frequency: 70, slope: 24 }, { type: "bell", frequency: 240, gain: -2.5, q: 1.1 },
             { type: "bell", frequency: 900, gain: -1.5, q: 1.4 }, { type: "bell", frequency: 4200, gain: 2, q: 0.9 },
             { type: "high_shelf", frequency: 11000, gain: 2.5, q: 0.7 }]),
      auto_gain: true, color_mode: "clean" }),
  p("Radio Voice", "Vocals", { Source: "Voice", Intent: "Presence", Intensity: "High" },
    { ...eq([{ type: "low_cut", frequency: 110, slope: 24 }, { type: "bell", frequency: 320, gain: -4, q: 1.2 },
             { type: "bell", frequency: 2600, gain: 3, q: 0.8 }, { type: "high_shelf", frequency: 9000, gain: 2, q: 0.7 }]),
      color_mode: "console", color_amount: 25, color_drive: 3 }),
  p("Kick Weight", "Drums", { Source: "Kick", Intent: "Weight", Intensity: "Medium" },
    { ...eq([{ type: "bell", frequency: 58, gain: 3, q: 1.1 }, { type: "bell", frequency: 300, gain: -4, q: 1.3 },
             { type: "bell", frequency: 3400, gain: 2.5, q: 1.0 }]), auto_gain: true }),
  p("Snare Crack", "Drums", { Source: "Snare", Intent: "Attack", Intensity: "High" },
    { ...eq([{ type: "low_cut", frequency: 90, slope: 24 }, { type: "bell", frequency: 220, gain: 2, q: 1.2 },
             { type: "bell", frequency: 800, gain: -2.5, q: 1.5 }, { type: "bell", frequency: 5200, gain: 3.5, q: 0.9 }]) }),
  p("Overhead Air", "Drums", { Source: "Overheads", Intent: "Air", Intensity: "Low" },
    { ...eq([{ type: "low_cut", frequency: 180, slope: 18 }, { type: "bell", frequency: 600, gain: -2, q: 1.1 },
             { type: "high_shelf", frequency: 12000, gain: 3, q: 0.7 }]) }),
  p("Bass Focus", "Bass", { Source: "Bass", Intent: "Focus", Intensity: "Medium" },
    { ...eq([{ type: "low_cut", frequency: 32, slope: 24 }, { type: "bell", frequency: 90, gain: 2, q: 1.0 },
             { type: "bell", frequency: 420, gain: -3, q: 1.4 }, { type: "bell", frequency: 1800, gain: 2, q: 1.1 }]),
      auto_gain: true }),
  p("Guitar Body Cut", "Guitars", { Source: "Electric Guitar", Intent: "Clarity", Intensity: "Medium" },
    { ...eq([{ type: "low_cut", frequency: 95, slope: 18 }, { type: "bell", frequency: 340, gain: -3.5, q: 1.3 },
             { type: "bell", frequency: 2400, gain: 2, q: 0.9 }, { type: "high_cut", frequency: 9000, slope: 12 }]) }),
  p("Acoustic Sparkle", "Guitars", { Source: "Acoustic", Intent: "Air", Intensity: "Low" },
    { ...eq([{ type: "low_cut", frequency: 80, slope: 18 }, { type: "bell", frequency: 260, gain: -2, q: 1.0 },
             { type: "bell", frequency: 3200, gain: 1.5, q: 0.8 }, { type: "high_shelf", frequency: 10000, gain: 3, q: 0.7 }]) }),
  p("Piano Lift", "Keys", { Source: "Piano", Intent: "Clarity", Intensity: "Low" },
    { ...eq([{ type: "bell", frequency: 180, gain: -1.5, q: 1.0 }, { type: "bell", frequency: 1200, gain: 1, q: 0.8 },
             { type: "high_shelf", frequency: 9000, gain: 2, q: 0.7 }]) }),
  p("Mix Glue Tilt", "Mix Bus", { Source: "Mix", Intent: "Balance", Intensity: "Low" },
    { ...eq([{ type: "low_shelf", frequency: 120, gain: 1, q: 0.7 }, { type: "bell", frequency: 420, gain: -1, q: 1.0 },
             { type: "high_shelf", frequency: 10000, gain: 1.5, q: 0.7 }]),
      color_mode: "tape", color_amount: 20, auto_gain: true }),
  p("Master Polish", "Master", { Source: "Master", Intent: "Polish", Intensity: "Low" },
    { ...eq([{ type: "low_cut", frequency: 24, slope: 24 }, { type: "bell", frequency: 220, gain: -0.8, q: 1.2 },
             { type: "high_shelf", frequency: 12000, gain: 1.2, q: 0.7 }]),
      processing_quality: "linear-phase", oversampling: "4x", auto_gain: true }),
  p("Surgical Notch", "Utility", { Source: "Any", Intent: "Repair", Intensity: "High" },
    { ...eq([{ type: "bell", frequency: 1000, gain: -12, q: 12 }]), auto_gain: false, analyzer: true }),
]);

// ==================================================== D02 FLUX DYNAMIC EQ
const d02 = bank("D02", [
  p("Vocal Sibilance Tame", "Vocals", { Source: "Lead Vocal", Intent: "Control", Intensity: "Medium" },
    { band_count: 3, adaptive: true,
      ...bands([{ frequency: 7200, q: 3.5, threshold: -28, range: -6, ratio: 4, attack: 1, release: 90, direction: "down" },
                { frequency: 320, q: 1.4, threshold: -22, range: -3, ratio: 2.5, attack: 20, release: 220, direction: "down" },
                { frequency: 3000, q: 1.2, threshold: -18, range: 2, ratio: 2, attack: 30, release: 250, direction: "up" }]) }),
  p("Boxy Voice Fix", "Vocals", { Source: "Voice", Intent: "Repair", Intensity: "Medium" },
    { band_count: 2,
      ...bands([{ frequency: 420, q: 2.0, threshold: -26, range: -5, ratio: 3, attack: 15, release: 180, direction: "down" },
                { frequency: 900, q: 1.8, threshold: -24, range: -3, ratio: 2.5, attack: 20, release: 200, direction: "down" }]) }),
  p("Kick Boom Control", "Drums", { Source: "Kick", Intent: "Control", Intensity: "High" },
    { band_count: 2,
      ...bands([{ frequency: 70, q: 1.6, threshold: -20, range: -6, ratio: 4, attack: 5, release: 120, direction: "down" },
                { frequency: 3500, q: 1.2, threshold: -24, range: 3, ratio: 2, attack: 2, release: 80, direction: "up" }]) }),
  p("Cymbal Harshness", "Drums", { Source: "Overheads", Intent: "Smooth", Intensity: "Medium" },
    { band_count: 2,
      ...bands([{ frequency: 6500, q: 2.4, threshold: -26, range: -5, ratio: 3, attack: 3, release: 140, direction: "down" },
                { frequency: 11000, q: 1.6, threshold: -30, range: -3, ratio: 2, attack: 5, release: 160, direction: "down" }]) }),
  p("Bass Note Evener", "Bass", { Source: "Bass", Intent: "Balance", Intensity: "Medium" },
    { band_count: 2, adaptive: true,
      ...bands([{ frequency: 95, q: 2.2, threshold: -22, range: -5, ratio: 4, attack: 10, release: 150, direction: "down" },
                { frequency: 190, q: 2.0, threshold: -24, range: -4, ratio: 3, attack: 12, release: 160, direction: "down" }]) }),
  p("Guitar Pick Tame", "Guitars", { Source: "Acoustic", Intent: "Smooth", Intensity: "Low" },
    { band_count: 1,
      ...bands([{ frequency: 2800, q: 2.0, threshold: -24, range: -4, ratio: 3, attack: 4, release: 120, direction: "down" }]) }),
  p("Amp Fizz Control", "Guitars", { Source: "Electric Guitar", Intent: "Smooth", Intensity: "Medium" },
    { band_count: 2,
      ...bands([{ frequency: 4200, q: 1.8, threshold: -22, range: -5, ratio: 3, attack: 6, release: 130, direction: "down" },
                { frequency: 240, q: 1.4, threshold: -20, range: -3, ratio: 2.5, attack: 18, release: 200, direction: "down" }]) }),
  p("Piano Resonance", "Keys", { Source: "Piano", Intent: "Repair", Intensity: "Low" },
    { band_count: 2,
      ...bands([{ frequency: 260, q: 3.0, threshold: -26, range: -4, ratio: 3, attack: 15, release: 180, direction: "down" },
                { frequency: 1500, q: 2.4, threshold: -28, range: -3, ratio: 2.5, attack: 12, release: 170, direction: "down" }]) }),
  p("Mix Bus Tighten", "Mix Bus", { Source: "Mix", Intent: "Control", Intensity: "Low" },
    { band_count: 2, adaptive: true,
      ...bands([{ frequency: 150, q: 1.2, threshold: -18, range: -2.5, ratio: 2, attack: 25, release: 250, direction: "down" },
                { frequency: 5200, q: 1.0, threshold: -20, range: -2, ratio: 2, attack: 10, release: 200, direction: "down" }]) }),
  p("Master Mud Sweep", "Master", { Source: "Master", Intent: "Clarity", Intensity: "Low" },
    { band_count: 1, adaptive: true,
      ...bands([{ frequency: 320, q: 1.4, threshold: -16, range: -2, ratio: 2, attack: 30, release: 300, direction: "down" }]) }),
  p("Duck The Lows", "Creative", { Source: "Any", Intent: "Space", Intensity: "High" },
    { band_count: 1, external_sc: true,
      ...bands([{ frequency: 120, q: 1.0, threshold: -30, range: -10, ratio: 6, attack: 2, release: 120, direction: "down" }]) }),
  p("Listen And Learn", "Utility", { Source: "Any", Intent: "Setup", Intensity: "Low" },
    { band_count: 1, auto_learn: true, delta: true,
      ...bands([{ frequency: 1000, q: 2.0, threshold: -24, range: -4, ratio: 3, attack: 15, release: 200, direction: "down", listen: true }]) }),
]);

// ================================================== D03 SPECTRA MULTIBAND
const d03 = bank("D03", [
  p("Mix Bus Control", "Mix Bus", { Source: "Mix", Intent: "Glue", Intensity: "Low" },
    { band_count: 4, ...xovers([120, 800, 5000]), global_link: 80, global_mix: 100,
      ...bands([{ threshold: -22, ratio: 2, attack: 30, release: 220, range: -4, makeup: 1 },
                { threshold: -20, ratio: 2, attack: 25, release: 200, range: -3, makeup: 0.5 },
                { threshold: -20, ratio: 2, attack: 15, release: 180, range: -3, makeup: 0.5 },
                { threshold: -24, ratio: 2.5, attack: 5, release: 150, range: -3, makeup: 1 }]) }),
  p("Master Tighten", "Master", { Source: "Master", Intent: "Control", Intensity: "Medium" },
    { band_count: 4, ...xovers([100, 700, 6000]), global_link: 100,
      ...bands([{ threshold: -18, ratio: 3, attack: 20, release: 180, range: -5, makeup: 1.5 },
                { threshold: -16, ratio: 2.5, attack: 20, release: 160, range: -4, makeup: 1 },
                { threshold: -16, ratio: 2.5, attack: 12, release: 140, range: -4, makeup: 1 },
                { threshold: -20, ratio: 3, attack: 4, release: 120, range: -4, makeup: 1.5 }]) }),
  p("Vocal Evener", "Vocals", { Source: "Lead Vocal", Intent: "Control", Intensity: "Medium" },
    { band_count: 3, ...xovers([300, 4000]), global_link: 60,
      ...bands([{ threshold: -26, ratio: 3, attack: 25, release: 200, range: -6, makeup: 2 },
                { threshold: -22, ratio: 2.5, attack: 15, release: 160, range: -5, makeup: 1.5 },
                { threshold: -28, ratio: 4, attack: 2, release: 100, range: -6, makeup: 2 }]) }),
  p("Drum Bus Punch", "Drums", { Source: "Drum Bus", Intent: "Punch", Intensity: "High" },
    { band_count: 3, ...xovers([160, 3000]), global_link: 50,
      ...bands([{ threshold: -20, ratio: 4, attack: 15, release: 120, range: -6, makeup: 2.5 },
                { threshold: -18, ratio: 3, attack: 25, release: 100, range: -5, makeup: 2 },
                { threshold: -22, ratio: 3, attack: 8, release: 90, range: -4, makeup: 1.5 }]) }),
  p("Kick And Bass Split", "Bass", { Source: "Bass", Intent: "Focus", Intensity: "Medium" },
    { band_count: 2, ...xovers([180]), global_link: 40,
      ...bands([{ threshold: -20, ratio: 4, attack: 10, release: 140, range: -6, makeup: 2 },
                { threshold: -22, ratio: 2.5, attack: 20, release: 160, range: -4, makeup: 1 }]) }),
  p("Guitar Bus Smooth", "Guitars", { Source: "Guitar Bus", Intent: "Smooth", Intensity: "Low" },
    { band_count: 3, ...xovers([200, 2500]),
      ...bands([{ threshold: -24, ratio: 2, attack: 30, release: 220, range: -3, makeup: 1 },
                { threshold: -22, ratio: 2, attack: 25, release: 200, range: -3, makeup: 1 },
                { threshold: -26, ratio: 2.5, attack: 10, release: 150, range: -4, makeup: 1.5 }]) }),
  p("Keys Level Hold", "Keys", { Source: "Keys", Intent: "Control", Intensity: "Low" },
    { band_count: 2, ...xovers([500]),
      ...bands([{ threshold: -24, ratio: 2, attack: 35, release: 250, range: -3, makeup: 1 },
                { threshold: -22, ratio: 2, attack: 25, release: 220, range: -3, makeup: 1 }]) }),
  p("Low End Tamer", "Utility", { Source: "Any", Intent: "Repair", Intensity: "High" },
    { band_count: 2, ...xovers([140]), global_link: 100,
      ...bands([{ threshold: -28, ratio: 6, attack: 8, release: 140, range: -10, makeup: 2 },
                { threshold: 0, ratio: 1, attack: 20, release: 200, range: 0, makeup: 0 }]) }),
  p("Upward Air", "Creative", { Source: "Mix", Intent: "Air", Intensity: "Medium" },
    { band_count: 3, ...xovers([250, 7000]),
      ...bands([{ threshold: -30, ratio: 2, mode: "compress", range: -2, attack: 30, release: 250 },
                { threshold: -30, ratio: 2, mode: "compress", range: -2, attack: 25, release: 220 },
                { threshold: -34, ratio: 2, mode: "expand_up", range: 4, attack: 15, release: 200 }]) }),
  p("Podcast Leveller", "Vocals", { Source: "Speech", Intent: "Consistency", Intensity: "High" },
    { band_count: 3, ...xovers([220, 5000]), global_link: 70,
      ...bands([{ threshold: -30, ratio: 4, attack: 20, release: 180, range: -8, makeup: 3 },
                { threshold: -28, ratio: 3.5, attack: 12, release: 150, range: -7, makeup: 3 },
                { threshold: -30, ratio: 4, attack: 3, release: 110, range: -6, makeup: 2.5 }]) }),
  p("Parallel Squeeze", "Creative", { Source: "Any", Intent: "Density", Intensity: "High" },
    { band_count: 4, ...xovers([120, 900, 6000]), global_mix: 45,
      ...bands([{ threshold: -34, ratio: 8, attack: 5, release: 90, range: -12, makeup: 4 },
                { threshold: -34, ratio: 8, attack: 5, release: 90, range: -12, makeup: 4 },
                { threshold: -34, ratio: 8, attack: 4, release: 80, range: -12, makeup: 4 },
                { threshold: -34, ratio: 8, attack: 2, release: 70, range: -12, makeup: 4 }]) }),
  p("Band Check", "Utility", { Source: "Any", Intent: "Setup", Intensity: "Low" },
    { band_count: 4, ...xovers([120, 800, 5000]), ...bands([{ solo: true }, {}, {}, {}]) }),
]);

// ====================================================== D04 PULSE LIMITER
const d04 = bank("D04", [
  p("Transparent Master", "Master", { Source: "Master", Intent: "Loudness", Intensity: "Low" },
    { threshold: -6, ceiling: -1, lookahead: 2, release: 250, release_mode: "adaptive", style: "transparent",
      transient_preserve: 60, oversampling: "8x", true_peak: true, target_lufs: -14 }),
  p("Streaming Safe", "Master", { Source: "Master", Intent: "Delivery", Intensity: "Low" },
    { threshold: -5, ceiling: -1, release: 220, style: "balanced", transient_preserve: 50, target_lufs: -14,
      true_peak: true, oversampling: "8x" }),
  p("Loud And Proud", "Master", { Source: "Master", Intent: "Loudness", Intensity: "High" },
    { threshold: -12, ceiling: -0.3, lookahead: 3, release: 120, release_mode: "manual", style: "dense",
      transient_preserve: 25, target_lufs: -7, oversampling: "16x" }),
  p("Club Master", "Master", { Source: "Electronic", Intent: "Loudness", Intensity: "High" },
    { threshold: -10, ceiling: -0.5, release: 90, style: "punch", transient_preserve: 45, target_lufs: -8 }),
  p("Mix Bus Safety", "Mix Bus", { Source: "Mix", Intent: "Safety", Intensity: "Low" },
    { threshold: -2, ceiling: -1.5, lookahead: 1, release: 300, style: "transparent", transient_preserve: 75 }),
  p("Drum Bus Ceiling", "Drums", { Source: "Drum Bus", Intent: "Control", Intensity: "Medium" },
    { threshold: -8, ceiling: -1, lookahead: 0.5, release: 80, style: "punch", transient_preserve: 70 }),
  p("Bass Peak Hold", "Bass", { Source: "Bass", Intent: "Control", Intensity: "Medium" },
    { threshold: -9, ceiling: -1, release: 150, style: "balanced", transient_preserve: 35, stereo_link: 100 }),
  p("Vocal Catch", "Vocals", { Source: "Lead Vocal", Intent: "Safety", Intensity: "Low" },
    { threshold: -6, ceiling: -1.5, lookahead: 1.5, release: 200, style: "transparent", transient_preserve: 55 }),
  p("Broadcast Leveller", "Utility", { Source: "Speech", Intent: "Delivery", Intensity: "Medium" },
    { threshold: -10, ceiling: -2, release: 260, style: "balanced", transient_preserve: 40, target_lufs: -16 }),
  p("Transient Keeper", "Creative", { Source: "Any", Intent: "Punch", Intensity: "Medium" },
    { threshold: -10, ceiling: -1, lookahead: 5, release: 60, style: "punch", transient_preserve: 100 }),
  p("Brick Wall", "Utility", { Source: "Any", Intent: "Safety", Intensity: "High" },
    { threshold: -3, ceiling: -0.1, lookahead: 8, release: 40, release_mode: "manual", style: "transparent",
      transient_preserve: 0, oversampling: "16x", true_peak: true }),
  p("Gain Reduction Listen", "Utility", { Source: "Any", Intent: "Setup", Intensity: "Low" },
    { threshold: -14, ceiling: -1, delta: true, style: "balanced" }),
]);

// ======================================================= D05 AIR DE-ESSER
const d05 = bank("D05", [
  p("Lead Vocal Ess", "Vocals", { Source: "Lead Vocal", Intent: "Control", Intensity: "Medium" },
    { threshold: -26, range: 8, focus: 6800, bandwidth: 1.2, attack: 1.5, release: 110, mode: "split", voice_profile: "neutral" }),
  p("Bright Singer", "Vocals", { Source: "Female Vocal", Intent: "Control", Intensity: "High" },
    { threshold: -30, range: 11, focus: 7800, bandwidth: 1.0, attack: 1, release: 90, mode: "split", voice_profile: "bright" }),
  p("Deep Voice", "Vocals", { Source: "Male Vocal", Intent: "Control", Intensity: "Medium" },
    { threshold: -24, range: 7, focus: 5600, bandwidth: 1.4, attack: 2, release: 130, mode: "split", voice_profile: "dark" }),
  p("Gentle Polish", "Vocals", { Source: "Lead Vocal", Intent: "Smooth", Intensity: "Low" },
    { threshold: -20, range: 4, focus: 7000, bandwidth: 1.6, attack: 3, release: 160, mode: "wide", sensitivity: -2 }),
  p("Rap Consonants", "Vocals", { Source: "Rap", Intent: "Control", Intensity: "High" },
    { threshold: -28, range: 10, focus: 6200, bandwidth: 1.0, attack: 0.5, release: 70, mode: "smart", sensitivity: 2 }),
  p("Backing Stack", "Vocals", { Source: "Backing Vocals", Intent: "Smooth", Intensity: "Medium" },
    { threshold: -26, range: 9, focus: 7200, bandwidth: 1.5, attack: 2, release: 140, mode: "wide", stereo_link: 100 }),
  p("Voice Over", "Utility", { Source: "Speech", Intent: "Consistency", Intensity: "Medium" },
    { threshold: -28, range: 9, focus: 6000, bandwidth: 1.3, attack: 1, release: 100, mode: "smart" }),
  p("Cymbal Sizzle", "Drums", { Source: "Overheads", Intent: "Smooth", Intensity: "Medium" },
    { threshold: -30, range: 7, focus: 9500, bandwidth: 2.2, attack: 1, release: 120, mode: "wide" }),
  p("Acoustic Pick Noise", "Guitars", { Source: "Acoustic", Intent: "Smooth", Intensity: "Low" },
    { threshold: -26, range: 6, focus: 4200, bandwidth: 1.8, attack: 2, release: 120, mode: "split" }),
  p("Mix Bus Harshness", "Mix Bus", { Source: "Mix", Intent: "Smooth", Intensity: "Low" },
    { threshold: -20, range: 4, focus: 5200, bandwidth: 2.6, attack: 4, release: 180, mode: "wide", sensitivity: -3 }),
  p("Hard Ess Repair", "Utility", { Source: "Any", Intent: "Repair", Intensity: "High" },
    { threshold: -34, range: 16, focus: 7000, bandwidth: 0.8, attack: 0.3, release: 60, mode: "split", sensitivity: 4 }),
  p("Listen To The Ess", "Utility", { Source: "Any", Intent: "Setup", Intensity: "Low" },
    { threshold: -26, range: 10, focus: 6800, bandwidth: 1.2, listen: true, mode: "split" }),
]);

// ===================================================== D06 RESONANCE CTRL
const d06 = bank("D06", [
  p("Vocal Resonance", "Vocals", { Source: "Lead Vocal", Intent: "Repair", Intensity: "Medium" },
    { depth: 45, selectivity: 65, speed: 55, sensitivity: 55, smooth: 40, low_freq: 150, high_freq: 9000, transient_keep: 70 }),
  p("Harsh Voice Fix", "Vocals", { Source: "Voice", Intent: "Smooth", Intensity: "High" },
    { depth: 65, selectivity: 75, speed: 70, sensitivity: 65, smooth: 30, low_freq: 1500, high_freq: 12000, transient_keep: 55 }),
  p("Acoustic Boom", "Guitars", { Source: "Acoustic", Intent: "Repair", Intensity: "Medium" },
    { depth: 55, selectivity: 80, speed: 45, sensitivity: 60, smooth: 45, low_freq: 80, high_freq: 600, transient_keep: 75 }),
  p("Amp Honk", "Guitars", { Source: "Electric Guitar", Intent: "Repair", Intensity: "Medium" },
    { depth: 50, selectivity: 70, speed: 50, sensitivity: 55, smooth: 40, low_freq: 400, high_freq: 3000, transient_keep: 65 }),
  p("Piano Ring", "Keys", { Source: "Piano", Intent: "Repair", Intensity: "Low" },
    { depth: 35, selectivity: 85, speed: 40, sensitivity: 50, smooth: 55, low_freq: 150, high_freq: 4000, transient_keep: 80 }),
  p("Cymbal Ring", "Drums", { Source: "Overheads", Intent: "Smooth", Intensity: "Medium" },
    { depth: 50, selectivity: 70, speed: 65, sensitivity: 60, smooth: 35, low_freq: 3000, high_freq: 16000, transient_keep: 60 }),
  p("Snare Ping", "Drums", { Source: "Snare", Intent: "Repair", Intensity: "Medium" },
    { depth: 55, selectivity: 90, speed: 60, sensitivity: 60, smooth: 30, low_freq: 200, high_freq: 2500, transient_keep: 85 }),
  p("Room Rumble", "Utility", { Source: "Any", Intent: "Repair", Intensity: "High" },
    { depth: 70, selectivity: 75, speed: 35, sensitivity: 70, smooth: 50, low_freq: 40, high_freq: 400, transient_keep: 60 }),
  p("Mix Bus Smooth", "Mix Bus", { Source: "Mix", Intent: "Smooth", Intensity: "Low" },
    { depth: 25, selectivity: 55, speed: 40, sensitivity: 45, smooth: 60, low_freq: 100, high_freq: 14000, transient_keep: 85 }),
  p("Master Gentle", "Master", { Source: "Master", Intent: "Polish", Intensity: "Low" },
    { depth: 18, selectivity: 50, speed: 35, sensitivity: 40, smooth: 70, low_freq: 60, high_freq: 16000, transient_keep: 90 }),
  p("Side Only Clean", "Creative", { Source: "Mix", Intent: "Space", Intensity: "Medium" },
    { depth: 45, selectivity: 65, speed: 50, sensitivity: 55, smooth: 45, stereo_mode: "side", transient_keep: 70 }),
  p("Hear What It Removes", "Utility", { Source: "Any", Intent: "Setup", Intensity: "Low" },
    { depth: 50, selectivity: 70, delta: true, learn: true }),
]);

// ======================================================= D07 FREQ SHAPER
const d07 = bank("D07", [
  p("Vocal Presence Lift", "Vocals", { Source: "Lead Vocal", Intent: "Presence", Intensity: "Medium" },
    { ...xovers([200, 1200, 5000]), global_mix: 45, direct: 0, punch: 15, auto_gain: true,
      ...zones([{ harmonics: 4, density: 40, width: 100, enabled: true },
                { harmonics: 8, density: 50, width: 100, enabled: true },
                { harmonics: 12, density: 55, width: 110, enabled: true },
                { harmonics: 9, density: 45, width: 120, enabled: true }]) }),
  p("Air Above", "Vocals", { Source: "Lead Vocal", Intent: "Air", Intensity: "Low" },
    { ...xovers([300, 2000, 8000]), global_mix: 35, punch: 0,
      ...zones([{ harmonics: 0, density: 30, width: 100, enabled: false },
                { harmonics: 3, density: 35, width: 100, enabled: true },
                { harmonics: 8, density: 45, width: 110, enabled: true },
                { harmonics: 16, density: 60, width: 130, enabled: true }]) }),
  p("Bass Harmonics", "Bass", { Source: "Bass", Intent: "Weight", Intensity: "High" },
    { ...xovers([120, 600, 3000]), global_mix: 55, punch: 25, auto_gain: true,
      ...zones([{ harmonics: 18, density: 70, width: 60, enabled: true },
                { harmonics: 12, density: 55, width: 80, enabled: true },
                { harmonics: 5, density: 40, width: 100, enabled: true },
                { harmonics: 0, density: 30, width: 100, enabled: false }]) }),
  p("Kick Beater", "Drums", { Source: "Kick", Intent: "Attack", Intensity: "High" },
    { ...xovers([90, 700, 3500]), global_mix: 50, punch: 45,
      ...zones([{ harmonics: 14, density: 65, width: 50, enabled: true },
                { harmonics: 4, density: 40, width: 80, enabled: true },
                { harmonics: 12, density: 55, width: 100, enabled: true },
                { harmonics: 6, density: 45, width: 100, enabled: true }]) }),
  p("Drum Bus Excite", "Drums", { Source: "Drum Bus", Intent: "Energy", Intensity: "Medium" },
    { ...xovers([150, 1000, 6000]), global_mix: 40, punch: 30,
      ...zones([{ harmonics: 8, density: 50, width: 80, enabled: true },
                { harmonics: 6, density: 45, width: 100, enabled: true },
                { harmonics: 10, density: 55, width: 120, enabled: true },
                { harmonics: 12, density: 60, width: 140, enabled: true }]) }),
  p("Guitar Bite", "Guitars", { Source: "Electric Guitar", Intent: "Presence", Intensity: "Medium" },
    { ...xovers([180, 900, 4000]), global_mix: 45, punch: 20,
      ...zones([{ harmonics: 3, density: 35, width: 90, enabled: true },
                { harmonics: 9, density: 50, width: 100, enabled: true },
                { harmonics: 14, density: 60, width: 110, enabled: true },
                { harmonics: 7, density: 45, width: 120, enabled: true }]) }),
  p("Acoustic Shimmer", "Guitars", { Source: "Acoustic", Intent: "Air", Intensity: "Low" },
    { ...xovers([250, 1500, 7000]), global_mix: 35,
      ...zones([{ harmonics: 2, density: 30, width: 90, enabled: true },
                { harmonics: 5, density: 40, width: 100, enabled: true },
                { harmonics: 10, density: 50, width: 120, enabled: true },
                { harmonics: 14, density: 55, width: 140, enabled: true }]) }),
  p("Keys Sparkle", "Keys", { Source: "Keys", Intent: "Air", Intensity: "Low" },
    { ...xovers([200, 1200, 6000]), global_mix: 30,
      ...zones([{ harmonics: 2, density: 30, width: 100, enabled: true },
                { harmonics: 4, density: 35, width: 100, enabled: true },
                { harmonics: 8, density: 45, width: 120, enabled: true },
                { harmonics: 11, density: 50, width: 130, enabled: true }]) }),
  p("Mix Bus Sheen", "Mix Bus", { Source: "Mix", Intent: "Polish", Intensity: "Low" },
    { ...xovers([120, 900, 7000]), global_mix: 25, auto_gain: true,
      ...zones([{ harmonics: 3, density: 35, width: 90, enabled: true },
                { harmonics: 3, density: 35, width: 100, enabled: true },
                { harmonics: 6, density: 40, width: 110, enabled: true },
                { harmonics: 9, density: 45, width: 120, enabled: true }]) }),
  p("Master Gloss", "Master", { Source: "Master", Intent: "Polish", Intensity: "Low" },
    { ...xovers([100, 1000, 8000]), global_mix: 18, punch: 8, auto_gain: true,
      ...zones([{ harmonics: 2, density: 30, width: 95, enabled: true },
                { harmonics: 2, density: 30, width: 100, enabled: true },
                { harmonics: 4, density: 35, width: 105, enabled: true },
                { harmonics: 7, density: 40, width: 115, enabled: true }]) }),
  p("Lo-Fi Grit", "Creative", { Source: "Any", Intent: "Character", Intensity: "High" },
    { ...xovers([200, 1000, 4000]), global_mix: 80, punch: -30, direct: -6,
      ...zones([{ harmonics: 24, density: 85, width: 40, enabled: true },
                { harmonics: 30, density: 90, width: 60, enabled: true },
                { harmonics: 26, density: 80, width: 70, enabled: true },
                { harmonics: 10, density: 60, width: 80, enabled: true }]) }),
  p("Zone Listen", "Utility", { Source: "Any", Intent: "Setup", Intensity: "Low" },
    { ...xovers([200, 1200, 5000]), global_mix: 100,
      ...zones([{ harmonics: 6, density: 50, width: 100, enabled: true, solo: true },
                { harmonics: 6, density: 50, width: 100, enabled: true },
                { harmonics: 6, density: 50, width: 100, enabled: true },
                { harmonics: 6, density: 50, width: 100, enabled: true }]) }),
]);

// ======================================================== D08 ORBIT DELAY
const d08 = bank("D08", [
  p("Vocal Quarter", "Vocals", { Source: "Lead Vocal", Intent: "Space", Intensity: "Low" },
    { tempo_sync: true, time: 500, feedback: 28, mix: 18, duck: 40, mod_rate: 0.3, mod_depth: 2,
      ...taps([{ time: 500, level: -4, pan: -30, filter: 6000, enabled: true },
               { time: 750, level: -10, pan: 30, filter: 4500, enabled: true }]) }),
  p("Slapback Vocal", "Vocals", { Source: "Lead Vocal", Intent: "Character", Intensity: "Low" },
    { tempo_sync: false, time: 110, feedback: 5, mix: 22, duck: 20, mod_depth: 0,
      ...taps([{ time: 110, level: -3, pan: 0, filter: 5000, enabled: true }]) }),
  p("Ping Pong Eighths", "Vocals", { Source: "Vocal", Intent: "Space", Intensity: "Medium" },
    { tempo_sync: true, time: 250, feedback: 40, mix: 25, duck: 35,
      ...taps([{ time: 250, level: -4, pan: -80, filter: 7000, enabled: true },
               { time: 500, level: -7, pan: 80, filter: 5500, enabled: true },
               { time: 750, level: -12, pan: -60, filter: 4000, enabled: true }]) }),
  p("Guitar Dotted", "Guitars", { Source: "Electric Guitar", Intent: "Space", Intensity: "Medium" },
    { tempo_sync: true, time: 375, feedback: 45, mix: 30, duck: 15, mod_rate: 0.25, mod_depth: 4,
      ...taps([{ time: 375, level: -3, pan: -50, filter: 4500, enabled: true },
               { time: 750, level: -9, pan: 50, filter: 3500, enabled: true }]) }),
  p("Ambient Wash", "Creative", { Source: "Any", Intent: "Space", Intensity: "High" },
    { tempo_sync: true, time: 1000, feedback: 70, mix: 45, duck: 10, mod_rate: 0.15, mod_depth: 12,
      ...taps([{ time: 1000, level: -3, pan: -70, filter: 3000, enabled: true },
               { time: 1500, level: -6, pan: 70, filter: 2500, enabled: true },
               { time: 2000, level: -10, pan: 0, filter: 2000, enabled: true }]) }),
  p("Dub Throw", "Creative", { Source: "Any", Intent: "Character", Intensity: "High" },
    { tempo_sync: true, time: 500, feedback: 82, mix: 40, duck: 25, mod_rate: 0.5, mod_depth: 8,
      ...taps([{ time: 500, level: -2, pan: -60, filter: 2200, enabled: true },
               { time: 1000, level: -8, pan: 60, filter: 1800, enabled: true }]) }),
  p("Snare Throw", "Drums", { Source: "Snare", Intent: "Space", Intensity: "Medium" },
    { tempo_sync: true, time: 375, feedback: 30, mix: 20, duck: 55,
      ...taps([{ time: 375, level: -5, pan: 40, filter: 5000, enabled: true }]) }),
  p("Drum Room Taps", "Drums", { Source: "Drum Bus", Intent: "Space", Intensity: "Low" },
    { tempo_sync: false, time: 60, feedback: 12, mix: 15, duck: 45,
      ...taps([{ time: 45, level: -8, pan: -40, filter: 6000, enabled: true },
               { time: 75, level: -11, pan: 40, filter: 5000, enabled: true }]) }),
  p("Keys Rhythm", "Keys", { Source: "Keys", Intent: "Movement", Intensity: "Medium" },
    { tempo_sync: true, time: 250, feedback: 35, mix: 28, duck: 20, mod_rate: 0.4, mod_depth: 5,
      ...taps([{ time: 250, level: -5, pan: -55, filter: 6000, enabled: true },
               { time: 375, level: -8, pan: 55, filter: 5000, enabled: true },
               { time: 625, level: -13, pan: 0, filter: 4000, enabled: true }]) }),
  p("Bass Short Double", "Bass", { Source: "Bass", Intent: "Weight", Intensity: "Low" },
    { tempo_sync: false, time: 28, feedback: 0, mix: 12, duck: 60, mod_depth: 0,
      ...taps([{ time: 28, level: -8, pan: 0, filter: 1200, enabled: true }]) }),
  p("Tape Echo Drift", "Creative", { Source: "Any", Intent: "Character", Intensity: "Medium" },
    { tempo_sync: false, time: 320, feedback: 55, mix: 30, duck: 20, mod_rate: 0.8, mod_depth: 16,
      ...taps([{ time: 320, level: -4, pan: 0, filter: 3200, enabled: true }]) }),
  p("Freeze Pad", "Creative", { Source: "Any", Intent: "Texture", Intensity: "High" },
    { tempo_sync: true, time: 750, feedback: 90, mix: 50, freeze: true, mod_rate: 0.2, mod_depth: 10,
      ...taps([{ time: 750, level: -3, pan: -70, filter: 2600, enabled: true },
               { time: 1125, level: -7, pan: 70, filter: 2200, enabled: true }]) }),
]);

// ====================================================== D09 SPACEVERB PRO
const d09 = bank("D09", [
  p("Vocal Plate", "Vocals", { Source: "Lead Vocal", Intent: "Space", Intensity: "Medium" },
    { pre_delay: 30, decay: 1.8, size: 45, density: 75, diffusion: 70, early_late: 20, low_damp: 0.9,
      high_damp: 0.7, width: 120, mix: 22, duck: 35 }),
  p("Vocal Hall", "Vocals", { Source: "Lead Vocal", Intent: "Space", Intensity: "Medium" },
    { pre_delay: 45, decay: 3.2, size: 80, density: 60, diffusion: 65, early_late: -10, low_damp: 0.8,
      high_damp: 0.5, width: 130, mix: 26, duck: 40 }),
  p("Tight Room", "Drums", { Source: "Drum Bus", Intent: "Space", Intensity: "Low" },
    { pre_delay: 8, decay: 0.7, size: 25, density: 80, diffusion: 75, early_late: 60, low_damp: 1.0,
      high_damp: 0.9, width: 100, mix: 18, duck: 45 }),
  p("Snare Chamber", "Drums", { Source: "Snare", Intent: "Space", Intensity: "Medium" },
    { pre_delay: 18, decay: 1.4, size: 40, density: 70, diffusion: 80, early_late: 10, low_damp: 0.9,
      high_damp: 0.7, width: 110, mix: 24, duck: 30 }),
  p("Guitar Spring", "Guitars", { Source: "Electric Guitar", Intent: "Character", Intensity: "Medium" },
    { pre_delay: 5, decay: 1.6, size: 30, density: 45, diffusion: 40, early_late: 40, low_damp: 1.2,
      high_damp: 0.8, width: 90, mix: 28 }),
  p("Acoustic Room", "Guitars", { Source: "Acoustic", Intent: "Space", Intensity: "Low" },
    { pre_delay: 15, decay: 1.2, size: 35, density: 65, diffusion: 70, early_late: 35, low_damp: 1.0,
      high_damp: 0.8, width: 110, mix: 16 }),
  p("Piano Concert", "Keys", { Source: "Piano", Intent: "Space", Intensity: "Medium" },
    { pre_delay: 25, decay: 2.6, size: 75, density: 60, diffusion: 65, early_late: -20, low_damp: 0.8,
      high_damp: 0.6, width: 130, mix: 20 }),
  p("Strings Cathedral", "Strings & Horns", { Source: "Strings", Intent: "Space", Intensity: "High" },
    { pre_delay: 60, decay: 6.5, size: 95, density: 55, diffusion: 60, early_late: -40, low_damp: 0.7,
      high_damp: 0.5, width: 150, mix: 32, mod_depth: 25 }),
  p("Mix Bus Depth", "Mix Bus", { Source: "Mix", Intent: "Depth", Intensity: "Low" },
    { pre_delay: 20, decay: 1.4, size: 50, density: 70, diffusion: 70, early_late: 30, low_damp: 1.0,
      high_damp: 0.7, width: 110, mix: 10, duck: 50 }),
  p("Infinite Pad", "Creative", { Source: "Any", Intent: "Texture", Intensity: "High" },
    { pre_delay: 80, decay: 20, size: 100, density: 50, diffusion: 55, early_late: -70, low_damp: 0.6,
      high_damp: 0.4, mod_rate: 0.2, mod_depth: 45, width: 160, mix: 55 }),
  p("Reverse Bloom", "Creative", { Source: "Any", Intent: "Texture", Intensity: "High" },
    { pre_delay: 120, decay: 4.5, size: 85, density: 40, diffusion: 45, early_late: -90, low_damp: 0.7,
      high_damp: 0.5, mod_rate: 0.6, mod_depth: 35, width: 150, mix: 45 }),
  p("Freeze Hold", "Creative", { Source: "Any", Intent: "Texture", Intensity: "High" },
    { pre_delay: 0, decay: 30, size: 100, density: 60, diffusion: 60, freeze: true, width: 140, mix: 50 }),
]);

// ======================================================= D10 WIDE IMAGER
const wide = (list) => Object.assign({}, ...list.map((w, i) => slot("band", i + 1, { width: w })));
const d10 = bank("D10", [
  p("Natural Spread", "Mix Bus", { Source: "Mix", Intent: "Width", Intensity: "Low" },
    { global_width: 115, bass_mono: 120, focus: 50, safe_width: true, ...xovers([150, 800, 4000]),
      ...wide([70, 110, 120, 125]) }),
  p("Wide Master", "Master", { Source: "Master", Intent: "Width", Intensity: "Medium" },
    { global_width: 125, bass_mono: 110, focus: 60, safe_width: true, ...xovers([140, 900, 5000]),
      ...wide([60, 115, 130, 140]) }),
  p("Mono Bass Lock", "Bass", { Source: "Bass", Intent: "Focus", Intensity: "High" },
    { global_width: 100, bass_mono: 250, focus: 70, safe_width: true, ...xovers([250, 1200, 6000]),
      ...wide([0, 100, 100, 100]) }),
  p("Drum Overhead Wide", "Drums", { Source: "Overheads", Intent: "Width", Intensity: "Medium" },
    { global_width: 130, bass_mono: 180, focus: 55, ...xovers([200, 1500, 7000]),
      ...wide([50, 120, 140, 150]) }),
  p("Guitar Double Spread", "Guitars", { Source: "Guitars", Intent: "Width", Intensity: "Medium" },
    { global_width: 140, bass_mono: 150, focus: 50, ...xovers([160, 1000, 5000]),
      ...wide([60, 130, 150, 155]) }),
  p("Keys Stereo Open", "Keys", { Source: "Keys", Intent: "Width", Intensity: "Low" },
    { global_width: 120, bass_mono: 130, focus: 45, ...xovers([150, 900, 4500]),
      ...wide([70, 115, 125, 135]) }),
  p("Vocal Centre Hold", "Vocals", { Source: "Lead Vocal", Intent: "Focus", Intensity: "Low" },
    { global_width: 95, bass_mono: 200, focus: 80, safe_width: true, ...xovers([200, 1200, 6000]),
      ...wide([40, 85, 95, 110]) }),
  p("Air Only Wide", "Master", { Source: "Master", Intent: "Air", Intensity: "Low" },
    { global_width: 105, bass_mono: 120, focus: 65, safe_width: true, ...xovers([120, 2000, 8000]),
      ...wide([70, 100, 110, 145]) }),
  p("Narrow And Tight", "Utility", { Source: "Any", Intent: "Focus", Intensity: "Medium" },
    { global_width: 70, bass_mono: 300, focus: 75, ...wide([0, 70, 75, 80]) }),
  p("Tilt Left", "Creative", { Source: "Any", Intent: "Position", Intensity: "Medium" },
    { global_width: 110, rotation: -18, ms_balance: -15, bass_mono: 140 }),
  p("Super Wide FX", "Creative", { Source: "Any", Intent: "Width", Intensity: "High" },
    { global_width: 200, bass_mono: 200, focus: 30, safe_width: false, ...xovers([180, 900, 4000]),
      ...wide([40, 180, 210, 230]) }),
  p("Mono Check", "Utility", { Source: "Any", Intent: "Setup", Intensity: "Low" },
    { mono_check: true, global_width: 100, safe_width: true }),
]);

const banks = { D01: d01, D02: d02, D03: d03, D04: d04, D05: d05,
                D06: d06, D07: d07, D08: d08, D09: d09, D10: d10 };

// --- validate every id against the contract before writing ---------------
const expand = (id, base) => {
  const slots = { D01: { band: 24, xover: 0 }, D02: { band: 12 }, D03: { band: 6, xover: 5 },
                  D07: { zone: 6, xover: 5 }, D08: { tap: 8 }, D10: { band: 5, xover: 4 } }[id] || {};
  const family = base.includes(".") ? base.split(".")[0] : "";
  return slots[family] ? slots[family] : 0;
};

let problems = 0;
for (const [id, data] of Object.entries(banks)) {
  const spec = JSON.parse(readFileSync(`specs/plugins/${id}.json`, "utf8"));
  const contract = new Set(spec.parameters.map((x) => x.id.split("\n")[0].trim()));
  for (const preset of data.presets)
    for (const key of Object.keys(preset.values)) {
      const base = key.replace(/\.(\d{2})\./, ".");
      const index = key.match(/\.(\d{2})\./);
      if (!contract.has(base)) { console.error(`${id} "${preset.name}": no such control ${key}`); ++problems; continue; }
      if (index && Number(index[1]) > expand(id, base)) { console.error(`${id} "${preset.name}": slot out of range ${key}`); ++problems; }
    }
  writeFileSync(`presets/factory/${id}_factory.json`, JSON.stringify(data, null, 2) + "\n");
  console.log(`${id}  ${data.presets.length} presets  ${data.categories.join(", ")}`);
}
console.log(problems === 0 ? "all ids check out against the contracts" : `${problems} problem(s)`);
process.exit(problems === 0 ? 0 : 1);
