<#
    Packages an Amanorsac product or bundle into a single self-contained
    Windows installer executable.

    The installer is per-user: it writes the VST3 bundles to the user's own
    VST3 folder and the standalone apps under LocalAppData, so it needs no
    administrator rights and cannot damage a machine-wide install.

    The build is NOT signed. Windows SmartScreen will warn on first run until
    an Authenticode certificate is added (see the launch audit, company P0).

    Usage:
        ./installer/build-windows-installer.ps1 -Version 1.0.0
        ./installer/build-windows-installer.ps1 -Version 1.0.0 -Stage "installer/stage/Amanorsac Analog Bundle"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Version,
    [string]$ProductName = "Amanorsac Analog Bundle",
    [string]$Stage = "",
    [string]$BuildDir = "build/win-x64",
    [string[]]$Targets = @("A01","A02","A03","A04","A05","A06","A07","A08","A09","A10"),
    [switch]$AllowUnarmed
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$slug = ($ProductName -replace "[^A-Za-z0-9]+", "_").Trim("_")
$stageDir = if ($Stage) { $Stage } else { Join-Path "installer/stage" $ProductName }

# ---------------------------------------------------------------- 1. stage
if (-not $Stage) {
    Write-Host "Staging payload from $BuildDir"
    if (Test-Path $stageDir) { Remove-Item $stageDir -Recurse -Force }
    New-Item -ItemType Directory -Force -Path (Join-Path $stageDir "VST3") | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $stageDir "Standalone") | Out-Null

    foreach ($id in $Targets) {
        $artefacts = Join-Path $BuildDir "Amanorsac${id}_artefacts/Release"
        $vst3 = Get-ChildItem (Join-Path $artefacts "VST3") -Filter *.vst3 -Directory -ErrorAction SilentlyContinue
        foreach ($bundle in $vst3) { Copy-Item $bundle.FullName (Join-Path $stageDir "VST3") -Recurse -Force }
        $apps = Get-ChildItem (Join-Path $artefacts "Standalone") -Filter *.exe -ErrorAction SilentlyContinue
        foreach ($app in $apps) { Copy-Item $app.FullName (Join-Path $stageDir "Standalone") -Force }
    }
}

# A customer installer must come from a build with licence enforcement armed.
$armedFile = Join-Path $BuildDir "licensing-armed.txt"
$armed = if (Test-Path $armedFile) { (Get-Content $armedFile -Raw).Trim() } else { "unknown" }
if ($armed -ne "1" -and -not $AllowUnarmed) {
    throw "This build has licence enforcement OFF (licensing-armed.txt = $armed). Reconfigure with -DAMANORSAC_LICENSING=ON, or pass -AllowUnarmed for an internal build."
}
if ($AllowUnarmed -and $armed -ne "1") { Write-Warning "Packaging an INTERNAL installer: the plug-ins do not require a licence." }
$bundleCount = (Get-ChildItem (Join-Path $stageDir "VST3") -Filter *.vst3 -Directory -ErrorAction SilentlyContinue).Count
$appCount = (Get-ChildItem (Join-Path $stageDir "Standalone") -Filter *.exe -ErrorAction SilentlyContinue).Count
Write-Host "Payload: $bundleCount VST3 bundles, $appCount standalone apps"
if ($bundleCount -lt 1 -or $appCount -lt 1) {
    throw "Nothing to package. Build the plug-ins first."
}
if ($bundleCount -ne $Targets.Count) {
    throw "Expected $($Targets.Count) VST3 bundles, found $bundleCount. Refusing to ship a partial bundle."
}

# ---------------------------------------------------------------- 2. payload
$payload = Join-Path $root "installer/stage/payload.zip"
if (Test-Path $payload) { Remove-Item $payload -Force }
Compress-Archive -Path (Join-Path $stageDir "*") -DestinationPath $payload -CompressionLevel Optimal
Write-Host ("Payload archive: {0:N1} MB" -f ((Get-Item $payload).Length / 1MB))

# ------------------------------------------------------- 3. stamp the bootstrapper
$buildInfo = @"
// Generated by installer/build-windows-installer.ps1. Do not edit by hand.
namespace AmanorsacInstaller;

internal static class BuildInfo
{
    public const string ProductName = "$ProductName";
    public const string Version = "$Version";
    public const int PluginCount = $bundleCount;
}
"@
Set-Content -Path (Join-Path $root "installer/Bootstrapper/BuildInfo.cs") -Value $buildInfo -Encoding utf8

# ---------------------------------------------------------------- 4. build
$assembly = "${slug}_${Version}_Windows"
dotnet publish installer/Bootstrapper/AmanorsacInstaller.csproj `
    -c Release -r win-x64 --self-contained true `
    -p:PayloadZip="$payload" -p:AssemblyName=$assembly `
    -o installer/stage/publish
if ($LASTEXITCODE -ne 0) { throw "Bootstrapper build failed" }

# ---------------------------------------------------------------- 5. deliver
New-Item -ItemType Directory -Force -Path (Join-Path $root "dist") | Out-Null
$exe = Join-Path $root "dist/$assembly.exe"
Copy-Item (Join-Path $root "installer/stage/publish/$assembly.exe") $exe -Force
(Get-FileHash $exe -Algorithm SHA256).Hash.ToLower() + "  $assembly.exe" |
    Set-Content -Path "$exe.sha256" -Encoding ascii

Write-Host ""
Write-Host "Installer: $exe"
Write-Host ("Size: {0:N1} MB" -f ((Get-Item $exe).Length / 1MB))
Write-Host "Signed: NO - SmartScreen will warn until an Authenticode certificate is wired in."
